version: "3"

tasks:
  #
  # sdk
  #

  sdk:test:
    dir: sdk/tests
    cmds:
      - api exec "tox"
  django:middleware:test:
    dir: frameworks/django/optic_django_middleware
    cmds:
      - tox
  django:unittest:test:
    dir: frameworks/django/optic_django_unittest
    cmds:
      - tox

  sdk:publish:
    desc: Publish optic-python-sdk
    dir: sdk
    cmds:
      - task: poetry:publish
        vars:
          PROJECT_DIR: sdk
  sdk:publish:test:
    desc: Publish optic-python-sdk to test pypi
    dir: sdk
    cmds:
      - task: poetry:publish:test
        vars:
          PROJECT_DIR: sdk
  django:middleware:publish:
    desc: Publish optic-python-django-middleware
    dir: frameworks/django/optic_django_middleware
    cmds:
      - task: poetry:publish
        vars:
          PROJECT_DIR: frameworks/django/optic_django_middleware
  django:middleware:publish:test:
    desc: Publish optic-python-django-middleware to test pypi
    dir: frameworks/django/optic_django_middleware
    cmds:
      - task: poetry:publish:test
        vars:
          PROJECT_DIR: frameworks/django/optic_django_middleware
  django:unittest-plugin:publish:
    desc: Publish optic-python-django-unittest-plugin
    dir: frameworks/django/optic_django_unittest
    cmds:
      - task: poetry:publish
        vars:
          PROJECT_DIR: frameworks/django/optic_django_unittest
  django:unittest-plugin:publish:test:
    desc: Publish optic-python-django-middleware to test pypi
    dir: frameworks/django/optic_django_unittest
    cmds:
      - task: poetry:publish:test
        vars:
          PROJECT_DIR: frameworks/django/optic_django_unittest
  test-all:
    cmds:
      - task: sdk:test
      - task: django:middleware:test
      - task: django:unittest:test

  poetry:publish:
    dir: "{{.PROJECT_DIR}}"
    vars:
      DRY_RUN: '{{default "false" .DRY_RUN}}'
    env:
      POETRY_PYPI_TOKEN_PYPI: "pypi-AgEIcHlwaS5vcmcCJDYyOTVkYWRmLWY3OTUtNDkyYi1hYWEwLTYyYTNiZGRjMGJiNwACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYg1AjE2Q9SBdN54iUGcD5Y1u0jLpzZLD-3n_5UdszTN8M"
    cmds:
      - poetry publish --build {{if (eq .DRY_RUN "true")}}--dry-run {{end}}

  poetry:publish:test:
    dir: "{{.PROJECT_DIR}}"
    vars:
      DRY_RUN: "{{default `false` .DRY_RUN}}"
    env:
      POETRY_PYPI_TOKEN_PYPI: "pypi-AgENdGVzdC5weXBpLm9yZwIkNjM2MDg1NDEtZjg2ZS00MjcwLWIxMjItOTFkZGZmZWVkZmNhAAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiBEhWvpGWqWxc1MDQAFTRd8zDjdhr9pAuGasb6YB_A3Fw"
      POETRY_HTTP_BASIC_TESTPYPI_USERNAME: "__token__"
      POETRY_HTTP_BASIC_TESTPYPI_PASSWORD: "<token>"
    cmds:
      - poetry config repositories.testpypi https://test.pypi.org/legacy/
      - poetry config pypi-token.testpypi "$POETRY_PYPI_TOKEN_PYPI"
      - poetry publish --build {{if (eq .DRY_RUN "true")}}--dry-run {{end}}--repository=testpypi


  git:tag-and-push:
    - git switch main
    - git pull --rebase
    - git tag {{.CLI_ARGS}}
    - git push origin main --tags

  publish-all:
    cmds:
      - task: sdk:publish
  test-publish-all:
    cmds:
      - task: sdk:publish:test
