name: Python package

on:
  create:
    branches: [ 'develop' ]
  push:
    branches: [ 'main' ]


env:
  DRY_RUN: false

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Task
        run: curl -sL https://taskfile.dev/install.sh | sudo bash -s -- -b /usr/local/bin/
      - name: Install dependencies
        run: |
          pip install poetry
      - name: Publish to PyPi
        if: ${{ github.event_name == 'push' }}
        run: task sdk:publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      - name: Publish to testPyPi
        if: ${{ github.event_name == 'create' }}
        run: task sdk:publish:test
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.TEST_PYPI_TOKEN }}
